name: Docker Image CI

on:
  #push:
  #  branches: [ "master" ]
  #pull_request:
  #  branches: [ "master" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    
    strategy:
      fail-fast: false # 其中一个失败不影响另一个继续构建
      matrix:
        include:
          - os_type: alpine
            base_image: httpd:alpine
            dockerfile: Dockerfile
          - os_type: debian
            base_image: httpd:latest
            dockerfile: Dockerfile-debian

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # 动态提取版本号步骤
      - name: Extract upstream versions
        id: vars
        run: |
          # 拉取当前 matrix 指定的底包
          docker pull ${{ matrix.base_image }}
          
          # 1. 提取 Apache 版本 (通用)
          HTTPD_VER=$(docker run --rm ${{ matrix.base_image }} httpd -v | head -n1 | sed 's/.*Apache\/\([0-9.]*\).*/\1/')
          
          # 2. 提取 OS 版本 (根据 os_type 判断)
          if [ "${{ matrix.os_type }}" = "alpine" ]; then
            OS_VER="alpine$(docker run --rm ${{ matrix.base_image }} cat /etc/alpine-release | tr -d '\r')"
          else
            OS_VER="debian$(docker run --rm ${{ matrix.base_image }} cat /etc/debian_version | tr -d '\r')"
          fi
          
          # 3. 组合 Tag
          DYNAMIC_TAG="${HTTPD_VER}-${OS_VER}"
          
          echo "dynamic_tag=$DYNAMIC_TAG" >> $GITHUB_OUTPUT
          echo "Detected: $DYNAMIC_TAG"

      - name: Extract metadate
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: |
            ghcr.io/driftingwind/webdav
            ${{ secrets.DOCKERHUB_USERNAME }}/webdav
          tags: |
            type=raw,value=${{ matrix.os_type }}
            type=raw,value=${{ steps.vars.outputs.dynamic_tag }}
            type=raw,value=latest,enable=${{ matrix.os_type == 'alpine' }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: "{{defaultContext}}:2.4"
          file: ${{ matrix.dockerfile }}
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          cache-from: type=gha
          cache-to: type=gha,mode=max